#!/usr/bin/env bash
# Task 32: idle auto-lock. Installs hypridle (Hyprland's own idle daemon,
# confirmed official `extra` repo, same family as hyprlock) and wires it to
# autostart via hyprland.lua, the same hl.on("hyprland.start", ...) pattern
# already used for quickshell (Task 10). The real hypridle.conf is
# generated (and regenerated on every Settings change) by jazz-idle-set,
# not this script - this only seeds a default idle-settings.json + initial
# hypridle.conf for a FRESH account (10 min, enabled - a reasonable default
# security posture, matching what comparable distros ship), and never
# overwrites a settings file that already exists, so re-running this script
# on an existing account (idempotent re-runs are this project's norm)
# doesn't clobber a user's own chosen timeout.
#
# Confirmed live on the Yoga 6, 14 Sept 2026, before writing this script: a
# short-timeout test listener genuinely triggered hyprlock and locked a
# real Wayland session (hypridle's own log: "Wayland session got locked").
#
# Run this ON THE INSTALLED GUEST, as root.
# Usage: setup-hypridle.sh <username>
set -euo pipefail

USERNAME="${1:?Usage: setup-hypridle.sh <username>}"
HOME_DIR="/home/$USERNAME"
HYPR_CONFIG="$HOME_DIR/.config/hypr/hyprland.lua"
SETTINGS_FILE="$HOME_DIR/.local/share/jazz/idle-settings.json"

pacman -Sy --noconfirm --needed hypridle

if [[ ! -f "$SETTINGS_FILE" ]]; then
    sudo -u "$USERNAME" env JAZZ_DATA_DIR="$HOME_DIR/.local/share/jazz" HOME="$HOME_DIR" \
        /usr/local/bin/jazz-idle-set --minutes 10 --enabled true > /dev/null
fi

if [[ -f "$HYPR_CONFIG" ]] && ! grep -q 'exec_cmd("hypridle")' "$HYPR_CONFIG"; then
    sudo -u "$USERNAME" tee -a "$HYPR_CONFIG" > /dev/null << 'EOF'

-- Added by setup-hypridle.sh (Task 32): autostart idle auto-lock. The real
-- timeout/enabled state lives in hypridle.conf, generated by jazz-idle-set
-- (called from Jazz Settings' Users tab) - this just launches the daemon,
-- which reads whatever config is on disk at that moment.
hl.on("hyprland.start", function()
    hl.exec_cmd("hypridle")
end)
EOF
fi

echo "Idle auto-lock prepared for $USERNAME:"
cat "$HOME_DIR/.config/hypr/hypridle.conf" 2>&1 | head -8 || true
