#!/usr/bin/env bash
# Task 27e: Qt/GTK compatibility layer for JAZZ's third-party apps (Task
# 15c's list) - JAZZ's own Quickshell/QML surfaces need no compatibility
# layer, this is purely for real Qt/GTK widget apps like VLC.
#
# Kvantum (kvantum/kvantum-qt5, confirmed official `extra` repo) recolors
# Qt5/Qt6 widget apps from a real per-JAZZ-theme .kvconfig, generated by
# jazz-theme-set (Task 27b's orchestrator) from a vendored KvArcDark
# template - see configs/kvantum/SOURCE.md for the base theme's origin/
# license, and jazz-theme-set's write_kvantum() for the substitution logic.
#
# GTK3: adw-gtk-theme (confirmed official `extra` repo - NOT the old
# AUR-only `adw-gtk3` package this project's earlier research assumed was
# the only option; re-checked live and it's since been packaged
# officially, so no manual vendoring or AUR helper is needed) ships both
# adw-gtk3 (light) and adw-gtk3-dark variants; jazz-theme-set's
# write_gtk3() picks the right one per theme mode via
# ~/.config/gtk-3.0/settings.ini (the standard freedesktop mechanism - no
# GTK_THEME env var override needed on top of it).
#
# Run this ON THE INSTALLED GUEST, as root, BEFORE setup-theme-bundle.sh
# (its default jazz-theme-set --restore call needs kvantum-base/ to
# already exist).
# Usage: setup-kvantum.sh <username>
set -eu

USERNAME="${1:?Usage: setup-kvantum.sh <username>}"
HOME_DIR="/home/$USERNAME"
DATA_DIR="$HOME_DIR/.local/share/jazz"
KVANTUM_BASE_SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/../configs/kvantum" && pwd)"
HYPR_CONFIG="$HOME_DIR/.config/hypr/hyprland.lua"

pacman -S --needed --noconfirm kvantum kvantum-qt5 adw-gtk-theme

sudo -u "$USERNAME" mkdir -p "$DATA_DIR/kvantum-base"
sudo -u "$USERNAME" cp "$KVANTUM_BASE_SRC/JazzBase.kvconfig" "$DATA_DIR/kvantum-base/"
sudo -u "$USERNAME" cp "$KVANTUM_BASE_SRC/JazzBase.svg" "$DATA_DIR/kvantum-base/"

if [[ -f "$HYPR_CONFIG" ]] && ! grep -q 'Added by setup-kvantum.sh' "$HYPR_CONFIG"; then
    sudo -u "$USERNAME" tee -a "$HYPR_CONFIG" > /dev/null << 'EOF'

-- Added by setup-kvantum.sh (Task 27e): force every Qt5/Qt6 app to use
-- Kvantum's widget style (jazz-theme-set writes the real per-theme content)
-- instead of each toolkit's own default (Breeze/Fusion) - same hl.env()
-- timing as setup-quickshell.sh's QT_* vars above.
hl.env("QT_STYLE_OVERRIDE", "kvantum")
EOF
fi

echo "Kvantum/GTK3 compat layer prepared for $USERNAME:"
ls -la "$DATA_DIR/kvantum-base/"
